//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UltimateDH_Value_HttpCallBackMessageWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UltimateDH.Value<HttpCallBackMessage>), typeof(System.Object), "Value_HttpCallBackMessage");
		L.RegFunction("Is", Is);
		L.RegFunction("AddChangeListener", AddChangeListener);
		L.RegFunction("RemoveChangeListener", RemoveChangeListener);
		L.RegFunction("ClearChangeListener", ClearChangeListener);
		L.RegFunction("SetFilter", SetFilter);
		L.RegFunction("Get", Get);
		L.RegFunction("GetLastValue", GetLastValue);
		L.RegFunction("Set", Set);
		L.RegFunction("SetAndForceUpdate", SetAndForceUpdate);
		L.RegFunction("SetAndDontUpdate", SetAndDontUpdate);
		L.RegFunction("New", _CreateUltimateDH_Value_HttpCallBackMessage);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegFunction("Filter", UltimateDH_Value_HttpCallBackMessage_Filter);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUltimateDH_Value_HttpCallBackMessage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				HttpCallBackMessage arg0 = (HttpCallBackMessage)ToLua.CheckObject<HttpCallBackMessage>(L, 1);
				UltimateDH.Value<HttpCallBackMessage> obj = new UltimateDH.Value<HttpCallBackMessage>(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UltimateDH.Value<HttpCallBackMessage>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Is(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			HttpCallBackMessage arg0 = (HttpCallBackMessage)ToLua.CheckObject<HttpCallBackMessage>(L, 2);
			bool o = obj.Is(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddChangeListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			System.Action<HttpCallBackMessage> arg0 = (System.Action<HttpCallBackMessage>)ToLua.CheckDelegate<System.Action<HttpCallBackMessage>>(L, 2);
			obj.AddChangeListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveChangeListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			System.Action<HttpCallBackMessage> arg0 = (System.Action<HttpCallBackMessage>)ToLua.CheckDelegate<System.Action<HttpCallBackMessage>>(L, 2);
			obj.RemoveChangeListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearChangeListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			obj.ClearChangeListener();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFilter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			UltimateDH.Value<HttpCallBackMessage>.Filter arg0 = (UltimateDH.Value<HttpCallBackMessage>.Filter)ToLua.CheckDelegate<UltimateDH.Value<HttpCallBackMessage>.Filter>(L, 2);
			obj.SetFilter(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Get(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			HttpCallBackMessage o = obj.Get();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLastValue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			HttpCallBackMessage o = obj.GetLastValue();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Set(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			HttpCallBackMessage arg0 = (HttpCallBackMessage)ToLua.CheckObject<HttpCallBackMessage>(L, 2);
			obj.Set(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAndForceUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			HttpCallBackMessage arg0 = (HttpCallBackMessage)ToLua.CheckObject<HttpCallBackMessage>(L, 2);
			obj.SetAndForceUpdate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAndDontUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UltimateDH.Value<HttpCallBackMessage> obj = (UltimateDH.Value<HttpCallBackMessage>)ToLua.CheckObject<UltimateDH.Value<HttpCallBackMessage>>(L, 1);
			HttpCallBackMessage arg0 = (HttpCallBackMessage)ToLua.CheckObject<HttpCallBackMessage>(L, 2);
			obj.SetAndDontUpdate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UltimateDH_Value_HttpCallBackMessage_Filter(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<UltimateDH.Value<HttpCallBackMessage>.Filter>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<UltimateDH.Value<HttpCallBackMessage>.Filter>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

